export enum Offsets {
    ServerConnectionUpdate,
    HasConnectFailed,
    MessageManagerReceiveMessage,
    HomePageStartGame,
    MessagingSend,
    NativeFontFormatString,
    MessageLength,
    ByteStream,
    MessageManagerInstance,
    CreateMessageByType,
    LogicLaserMessageFactory,
    Version,
    PayloadSize,
    PayloadPtr,
    Decode,
    OperatorNew,
    StringConstructor,
    State,
    GetMessageType = Process.pointerSize * 5,
    Destruct = Process.pointerSize * 7,
}